[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Brochure Redirect
[[redirects]]
  from = "/brochure"
  to = "https://www.notion.so/Woodfrog-Tech-Brochure-2242428418a880898d34cc88c64851b1"
  status = 301 # This tells browsers it's a permanent redirect

# Trajectory Redirect
[[redirects]]
  from = "/trajectory"
  to = "https://www.notion.so/Woodfrog-Tech-Trajectory-2492428418a88045bde5dab89c37b0ca"
  status = 301 # This tells browsers it's a permanent redirect